(() => {
  'use strict';
  const $=s=>document.querySelector(s),form=$('#invite-form'),key='negar-hossein-invitations-v3',fa=n=>new Intl.NumberFormat('fa-IR').format(n);
  const trashKey=key+'-deleted';let deleted=[];try{const saved=JSON.parse(localStorage.getItem(trashKey)||'[]');if(Array.isArray(saved))deleted=saved;}catch{}
  let guests=[];try{guests=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(guests))guests=[];}catch{$('#manager-status').textContent='ذخیرهٔ مرورگر در دسترس نیست؛ پس از ساخت دعوت حتماً پشتیبان بگیر.';}
  function fullname(){return [form.elements.title.value,form.elements.name.value.trim(),form.elements.family.value].filter(Boolean).join(' ');}
  function preview(){$('#invite-preview').textContent=`${fullname()||'نام مهمان'} · دعوت برای ${fa(Number(form.elements.seats.value)||0)} نفر`;}form.addEventListener('input',preview);preview();
  function link(g){const url=new URL('./',location.href);url.hash='invite='+new URLSearchParams({id:g.id,name:g.name,seats:String(g.seats),tier:g.tier});return url.href;}
  function showLink(g){const url=link(g);$('#invitation-link').value=url;$('#open-invitation').href=url;$('#link-result').hidden=false;}
  async function copy(value){try{await navigator.clipboard.writeText(value);$('#manager-status').textContent='لینک کپی شد؛ آمادهٔ ارسال برای همین مهمان است.';}catch{$('#manager-status').textContent='لینک را از کادر بالا انتخاب و کپی کن.';$('#invitation-link').focus();$('#invitation-link').select();}}
  function save(){try{localStorage.setItem(key,JSON.stringify(guests));return true;}catch{$('#manager-status').textContent='ذخیره در مرورگر ممکن نشد؛ همین حالا پشتیبان بگیر.';return false;}}
  function saveLists(next,nextDeleted){try{localStorage.setItem(trashKey,JSON.stringify(nextDeleted));localStorage.setItem(key,JSON.stringify(next));guests=next;deleted=nextDeleted;return true;}catch{try{localStorage.setItem(trashKey,JSON.stringify(deleted));}catch{}$('#delete-status').textContent='تغییر ذخیره نشد؛ دعوت از فهرست حذف نشده است.';return false;}}
  function removeGuest(g){const next=guests.filter(item=>item.id!==g.id);if(!saveLists(next,[...deleted.filter(item=>item.id!==g.id),g]))return;if($('#invitation-link').value===link(g)){$('#link-result').hidden=true;$('#invitation-link').value='';$('#open-invitation').removeAttribute('href');}render();$('#delete-status').textContent=`دعوتِ ${g.name} حذف شد؛ ${fa(g.seats)} نفر از تعداد دعوت‌شده کم شد.`;}
  $('#undo-delete').addEventListener('click',()=>{const g=deleted[deleted.length-1];if(!g)return;const next=guests.some(item=>item.id===g.id)?guests:[...guests,g];if(!saveLists(next,deleted.slice(0,-1)))return;render();$('#delete-status').textContent=`دعوتِ ${g.name} به فهرست برگشت.`;});
  function render(){window.renderWeddingReport(guests,deleted.map(g=>g.id));$('#undo-delete').hidden=!deleted.length;const list=$('#guest-list');list.replaceChildren();$('#totals').textContent=`${fa(guests.length)} دعوت‌نامه · ${fa(guests.reduce((n,g)=>n+g.seats,0))} نفر دعوت‌شده`;
    for(const g of [...guests].reverse()){const item=document.createElement('article');item.className='guest-entry';const name=document.createElement('strong');name.textContent=g.name;const detail=document.createElement('p');detail.textContent=`${fa(g.seats)} نفر · ${g.tier==='aqd'?'عقد و مراسم، از ساعت ۱۸':'مراسم، از ساعت ۱۹'}`;const id=document.createElement('small');id.textContent=`شناسه: ${g.id}`;const button=document.createElement('button');button.type='button';button.textContent='نمایش و کپی لینک';button.addEventListener('click',()=>{showLink(g);copy(link(g));});const actions=document.createElement('div');actions.className='actions guest-actions';const remove=document.createElement('button');remove.type='button';remove.className='delete-invite';remove.textContent='حذف دعوت';remove.setAttribute('aria-label','حذف دعوت '+g.name);remove.addEventListener('click',()=>removeGuest(g));actions.append(button,remove);item.append(name,detail,id,actions);list.append(item);}
  }
  form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const seats=Number(form.elements.seats.value);if(!Number.isInteger(seats)||seats<1||seats>100)return;const g={id:crypto.randomUUID(),name:fullname(),seats,tier:form.elements.tier.value,created:new Date().toISOString()};guests.push(g);const saved=save();showLink(g);render();if(saved)$('#manager-status').textContent='دعوت ذخیره شد. لینک بالا را برای مهمان بفرست.';});
  $('#copy-link').addEventListener('click',()=>copy($('#invitation-link').value));
  $('#backup').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:3,guests},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='negar-hossein-invitations.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);});
  $('#restore').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5000000)throw Error();const data=JSON.parse(await file.text());if(data.version!==3||!Array.isArray(data.guests)||data.guests.some(g=>typeof g.id!=='string'||!g.id||typeof g.name!=='string'||g.name.length>160||!Number.isInteger(g.seats)||g.seats<1||g.seats>100||!['aqd','ceremony'].includes(g.tier)))throw Error();const known=new Set(guests.map(g=>g.id));for(const g of data.guests){if(!known.has(g.id)){guests.push(g);known.add(g.id);}}const saved=save();render();if(saved)$('#manager-status').textContent='دعوت‌های پشتیبان به فهرست اضافه شدند.';}catch{$('#manager-status').textContent='فایل پشتیبان معتبر نیست.';}finally{e.target.value='';}});render();
})();
