(() => {
'use strict';
const API='https://negar-hossein-notifications.hosseinkarimi7000.chatgpt.site/api/',fa=n=>new Intl.NumberFormat('fa-IR').format(n);
const box=document.createElement('section');box.className='notification-admin';box.id='notifications-panel';
box.innerHTML='<h2>اطلاع‌رسانی به مهمان‌ها</h2><form id="push-login"><label>کد ورود به اطلاع‌رسانی<input name="code" type="password" autocomplete="current-password" required></label><button>ورود</button></form><div id="push-controls" hidden><div class="actions"><button id="push-refresh" type="button">به‌روزرسانی مشترکان</button><button id="push-logout" type="button">خروج</button></div><p id="push-subs"></p><details><summary>نام دعوت‌های دارای اشتراک</summary><div id="push-sub-list"></div></details><form id="push-compose"><label>گیرندگان<select name="audience"><option value="all">همه مشترکان</option><option value="aqd">عقد و مراسم</option><option value="ceremony">فقط مراسم</option><option value="pending">بی‌پاسخ‌ها؛ با دریافت تازه از گوگل</option><option value="guest">دعوت مشخص</option><option value="test">آزمایش فقط روی یک دستگاه</option></select></label><label>دعوت مشخص<select name="guestId"></select></label><label>دستگاه آزمایشی<select name="subscriptionId"></select></label><label>عنوان اعلان<input name="title" maxlength="80" required placeholder="خبرهای مراسم نگار و حسین"></label><label>پیام<textarea name="body" maxlength="500" rows="4" required></textarea></label><label>اعتبار پیام<select name="hours"><option value="6">۶ ساعت</option><option value="1">۱ ساعت</option><option value="12">۱۲ ساعت</option><option value="24">۲۴ ساعت</option></select></label><button id="push-preview" type="submit">بررسی گیرندگان و پیش‌نمایش</button></form><div id="push-review" hidden><strong id="push-review-title"></strong><p id="push-review-body"></p><p id="push-review-count"></p><button id="push-send" type="button">ارسال همین پیام</button><button id="push-edit" type="button">ویرایش</button></div><p>برای ادامه صف ارسال و تلاش‌های مجدد، این پنل را باز نگه دارید. بستن پنل صف را حفظ می‌کند؛ با ورود دوباره ادامه پیدا می‌کند. لغو پیام، اعلان‌هایی را که قبلاً ارسال شده‌اند از گوشی پاک نمی‌کند.</p><div id="push-history"></div></div><p id="push-status" role="status" aria-live="polite"></p>';
document.querySelector('#attendance-report').after(box);
const $=s=>box.querySelector(s),status=$('#push-status'),form=$('#push-compose');let token='',draft=null,timer=null,processing=false;
try{token=sessionStorage.getItem('wedding-push-admin')||'';}catch{}
async function call(path,data){const r=await fetch(API+'admin/'+path,{method:data?'POST':'GET',headers:{Authorization:'Bearer '+token,...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(60000)});const result=await r.json();if(!r.ok)throw Error(result.error||'اتصال برقرار نشد.');return result;}
function logged(on){$('#push-controls').hidden=!on;$('#push-login').hidden=on;}
async function sync(required=false){const snapshot=await window.getWeddingNotificationSnapshot(required);if(!snapshot.guests.length)throw Error('فهرست دعوت‌ها هنوز آماده نیست؛ فهرست نگار را دریافت کنید یا پشتیبان را وارد کنید.');await call('sync',snapshot);const select=form.elements.guestId,current=select.value;select.replaceChildren();for(const g of snapshot.guests){const op=document.createElement('option');op.value=g.id;op.textContent=g.name;select.append(op);}if(current)select.value=current;return snapshot;}
const labels={queued:'در صف',sending:'در حال ارسال',retry:'منتظر تلاش مجدد',accepted:'پذیرفته‌شده توسط سرویس؛ دریافت گوشی قطعی نیست',expired:'منقضی‌شده',unknown:'نتیجه نامشخص؛ برای جلوگیری از تکرار، خودکار تکرار نمی‌شود',failed:'ناموفق',cancelled:'لغوشده'};
async function refresh(){const r=await call('status');logged(true);const devices=form.elements.subscriptionId,chosen=devices.value;devices.replaceChildren();for(const d of r.devices){const op=document.createElement('option');op.value=d.id;op.dataset.guestId=d.guest_id;op.textContent=(d.name||'هنوز تطبیق داده نشده')+' · '+d.id.slice(0,6);devices.append(op);}if(chosen)devices.value=chosen;$('#push-subs').textContent=fa(r.subscriptions.length)+' دعوت دارای اشتراک · '+fa(r.subscriptions.reduce((n,s)=>n+s.devices,0))+' دستگاه فعال';$('#push-sub-list').replaceChildren();for(const s of r.subscriptions){const p=document.createElement('p');p.textContent=(s.name||'دعوت هنوز تطبیق داده نشده')+' · '+fa(s.devices)+' دستگاه';$('#push-sub-list').append(p);}const history=$('#push-history');history.replaceChildren();for(const c of r.campaigns){const a=document.createElement('article'),h=document.createElement('strong');h.textContent=c.title;a.append(h);for(const row of r.totals.filter(t=>t.campaign_id===c.id)){const p=document.createElement('p');p.textContent=labels[row.status]+': '+fa(row.count)+' · ثبت نمایش توسط دستگاه: '+fa(row.displayed||0)+' · کلیک: '+fa(row.clicked||0);a.append(p);}if(!c.cancelled&&c.expires>Date.now()){const cancel=document.createElement('button');cancel.type='button';cancel.textContent='لغو ادامه ارسال و خبر داخل کارت';cancel.addEventListener('click',async()=>{try{await call('cancel',{id:c.id});await refresh();}catch(e){status.textContent=e.message;}});a.append(cancel);}else{const p=document.createElement('p');p.textContent=c.cancelled?'این پیام لغو شده است.':'اعتبار این پیام تمام شده است.';a.append(p);}history.append(a);}return r;}
async function pump(){if(processing||!token)return;processing=true;try{const r=await call('status');for(const c of r.campaigns){if(r.totals.some(t=>t.campaign_id===c.id&&['queued','retry','sending'].includes(t.status)))await call('process',{id:c.id});}await refresh();}catch(e){status.textContent='ادامه ارسال متوقف شد: '+e.message+'؛ صف حفظ شده است.';}finally{processing=false;}}
async function login(){await call('status');logged(true);await sync(false);await refresh();clearInterval(timer);timer=setInterval(pump,10000);pump();status.textContent='متصل شد. ابتدا پیام را آزمایش کنید، سپس گیرندگان را بررسی کنید.';}
$('#push-login').addEventListener('submit',async e=>{e.preventDefault();token=e.target.elements.code.value.trim();try{await login();sessionStorage.setItem('wedding-push-admin',token);e.target.reset();}catch(e){status.textContent=e.message;}});
$('#push-logout').addEventListener('click',()=>{token='';sessionStorage.removeItem('wedding-push-admin');clearInterval(timer);draft=null;logged(false);$('#push-history').replaceChildren();status.textContent='خارج شدید.';});
$('#push-refresh').addEventListener('click',async()=>{try{status.textContent='در حال تطبیق دعوت‌ها و دریافت مشترکان…';await sync(false);await refresh();status.textContent='اطلاعات به‌روز شد.';}catch(e){status.textContent=e.message;}});
function selection(){return {audience:form.elements.audience.value,guestId:form.elements.audience.value==='test'?form.elements.subscriptionId.selectedOptions[0]?.dataset.guestId:form.elements.guestId.value,subscriptionId:form.elements.subscriptionId.value};}
function edit(){draft=null;$('#push-review').hidden=true;$('#push-send').disabled=false;form.hidden=false;}
$('#push-edit').addEventListener('click',edit);form.addEventListener('input',()=>{draft=null;});
form.addEventListener('submit',async e=>{e.preventDefault();$('#push-preview').disabled=true;try{status.textContent='در حال بررسی گیرندگان…';await sync(form.elements.audience.value==='pending');const selectionData=selection(),p=await call('preview',selectionData);draft={...selectionData,id:crypto.randomUUID(),signature:p.signature,title:form.elements.title.value.trim(),body:form.elements.body.value.trim(),hours:Number(form.elements.hours.value)};$('#push-review-title').textContent=draft.title;$('#push-review-body').textContent=draft.body;$('#push-review-count').textContent=fa(p.total)+' دعوت در گروه · '+fa(p.subscribedGuests)+' دعوت دارای اشتراک · ارسال به '+fa(p.devices)+' دستگاه؛ '+fa(p.total-p.subscribedGuests)+' دعوت نوتیف دریافت نمی‌کنند.';form.hidden=true;$('#push-review').hidden=false;$('#push-send').disabled=!p.devices;status.textContent=p.devices?'متن و تعداد گیرندگان را بررسی کنید.':'در این گروه هنوز دستگاه فعالی ثبت نشده است.';}catch(e){status.textContent=e.message;}finally{$('#push-preview').disabled=false;}});
$('#push-send').addEventListener('click',async()=>{if(!draft)return;$('#push-send').disabled=true;try{if(draft.audience==='pending')await sync(true);await call('create',draft);status.textContent='پیام در صف ثبت شد؛ نتیجه ارسال پایین نمایش داده می‌شود.';edit();await pump();}catch(e){status.textContent=e.message+' اگر اتصال قطع شده، تلاش دوباره با همین پیام ارسال تکراری نمی‌سازد.';$('#push-send').disabled=false;}});
if(token)login().catch(e=>{logged(false);status.textContent=e.message;});
})();
