(function(root){
'use strict';
function parseCSV(text){const rows=[];let row=[],value='',quoted=false;const s=text.replace(/^\uFEFF/,'');for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(quoted&&s[i+1]==='"'){value+='"';i++;}else if(!quoted&&value!=='')throw Error('CSV نامعتبر');else quoted=!quoted;}else if(c===','&&!quoted){row.push(value);value='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&s[i+1]==='\n')i++;row.push(value);if(row.some(v=>v!==''))rows.push(row);row=[];value='';}else value+=c;}if(quoted)throw Error('CSV نامعتبر');row.push(value);if(row.some(v=>v!==''))rows.push(row);return rows;}
function records(text){const [headers,...rows]=parseCSV(text);if(!headers||!headers.includes('guest_id')||!headers.includes('confirmed_count'))throw Error('فایل باید خروجی پاسخ‌های همین فرم و دارای شناسهٔ مهمان باشد.');return rows.map(row=>Object.fromEntries(headers.map((h,i)=>[h.trim(),row[i]||''])));}
function latest(records){const map=new Map();for(const r of records){if(!r.guest_id)continue;const old=map.get(r.guest_id);const date=x=>Date.parse(x.response_time||x.created_at||x.createdAt||x._date||x.date||x['Submitted At']||'')||0;if(!old||date(r)>date(old))map.set(r.guest_id,r);}return map;}
function csvCell(v){let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
const api={parseCSV,records,latest,csvCell};if(typeof module!=='undefined'){module.exports=api;return;}root.WeddingReport=api;
const key='negar-hossein-responses-v4';let responses=[];try{responses=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(responses))responses=[];}catch{}
let guests=[];
const message=r=>[r.message||'',r.additional_guests&&r.additional_guests!=='[]'?'همراهان اضافه: '+r.additional_guests:''].filter(Boolean).join('\n');
function rows(){const reply=latest(responses);return guests.map(g=>{const r=reply.get(g.id);return [g.name,g.seats,r?r.confirmed_count:'',r?(r.attendance==='yes'?'می‌آیند':'نمی‌آیند'):'هنوز پاسخ نداده',r?message(r):'',g.id];});}
root.renderWeddingReport=function(list){guests=list;const body=document.querySelector('#response-report tbody');body.replaceChildren();for(const row of rows()){const tr=document.createElement('tr');for(const v of row.slice(0,5)){const td=document.createElement('td');td.textContent=v;tr.append(td);}body.append(tr);}};
document.querySelector('#responses-import').addEventListener('change',async e=>{const status=document.querySelector('#report-status');try{const file=e.target.files[0];if(!file)return;if(file.size>10000000)throw Error('حجم فایل بیش از حد است.');responses=records(await file.text());let saved=true;try{localStorage.setItem(key,JSON.stringify(responses));}catch{saved=false;}root.renderWeddingReport(guests);status.textContent=responses.length+' پاسخ وارد شد. '+(saved?'':'ذخیرهٔ مرورگر ممکن نشد؛ گزارش را دریافت کن.');}catch(error){status.textContent=error.message;}finally{e.target.value='';}});
document.querySelector('#report-export').addEventListener('click',()=>{const all=[['دعوت‌شونده','تعداد دعوت اولیه','تعداد تأییدشده','وضعیت','پیام و همراهان','شناسه'],...rows()];const url=URL.createObjectURL(new Blob(['\uFEFF'+all.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='negar-hossein-attendance.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);});
})(typeof window==='undefined'?{}:window);
