(function(root){
'use strict';
function parseCSV(text){const rows=[];let row=[],value='',quoted=false;const s=text.replace(/^\uFEFF/,'');for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(quoted&&s[i+1]==='"'){value+='"';i++;}else if(!quoted&&value!=='')throw Error('CSV نامعتبر');else quoted=!quoted;}else if(c===','&&!quoted){row.push(value);value='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&s[i+1]==='\n')i++;row.push(value);if(row.some(v=>v!==''))rows.push(row);row=[];value='';}else value+=c;}if(quoted)throw Error('CSV نامعتبر');row.push(value);if(row.some(v=>v!==''))rows.push(row);return rows;}
function records(text){const [headers,...rows]=parseCSV(text);if(!headers||!headers.includes('guest_id')||!headers.includes('confirmed_count'))throw Error('فایل باید خروجی پاسخ‌های همین فرم و دارای شناسهٔ مهمان باشد.');return rows.map(row=>Object.fromEntries(headers.map((h,i)=>[h.trim(),row[i]||''])));}
function date(r){return Date.parse(r.response_time||r.created_at||r.createdAt||r._date||r.date||r['Submitted At']||'')||0;}
function latest(records){const map=new Map();for(const r of records){if(!r.guest_id)continue;const old=map.get(r.guest_id);if(!old||date(r)>date(old))map.set(r.guest_id,r);}return map;}
function merge(a,b){const map=new Map();for(const r of [...a,...b]){if(!r||typeof r.guest_id!=='string'||!r.guest_id)continue;const signature=JSON.stringify([r.guest_id,date(r),r.attendance,Number(r.confirmed_count),String(r.message||'').trim(),r.additional_guests||'[]']);map.set(signature,r);}return [...map.values()];}
function extras(r){try{const list=typeof r.additional_guests==='string'?JSON.parse(r.additional_guests):r.additional_guests;return Array.isArray(list)?list.map(p=>[p.name,p.relationship].filter(Boolean).join(' — ')).join('، '):'';}catch{return '';}}
function build(records,guests=[],excluded=[]){const skip=new Set(excluded),last=latest(records),names=new Map(guests.map(g=>[g.id,g]));const ids=[...new Set([...last.keys(),...names.keys()])].filter(id=>!skip.has(id));return ids.map(id=>{const r=last.get(id),g=names.get(id),history=records.filter(x=>x.guest_id===id).sort((a,b)=>date(b)-date(a));const messages=[...new Set(history.map(x=>String(x.message||'').trim()).filter(Boolean))];const yes=r?.attendance==='yes',no=r?.attendance==='no',number=Number(r?.confirmed_count);return {id,name:g?.name||r?.invitation_name||r?.name||'مهمان',invited:g?.seats??r?.invited_count??'',count:no?0:yes&&Number.isInteger(number)&&number>=0?number:null,status:yes?'yes':no?'no':r?'unknown':'pending',messages,extras:r?extras(r):'',date:r?date(r):0,submissions:history.length};}).sort((a,b)=>b.date-a.date);}
function summary(rows){return {confirmed:rows.reduce((sum,r)=>sum+(r.status==='yes'?(r.count||0):0),0),yes:rows.filter(r=>r.status==='yes').length,no:rows.filter(r=>r.status==='no').length,pending:rows.filter(r=>r.status==='pending').length,duplicates:rows.reduce((sum,r)=>sum+Math.max(0,r.submissions-1),0)};}
function csvCell(v){let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
const api={parseCSV,records,latest,merge,build,summary,csvCell};if(typeof module!=='undefined'){module.exports=api;return;}root.WeddingReport=api;
const $=s=>document.querySelector(s),fa=n=>new Intl.NumberFormat('fa-IR').format(n),key='negar-hossein-responses-v4',metaKey=key+'-updated';let responses=[],guests=[],excluded=[],meta=null,busy=false;
try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))responses=saved;meta=JSON.parse(localStorage.getItem(metaKey)||'null');}catch{}
function when(time){return time?new Date(time).toLocaleString('fa-IR',{timeZone:'Asia/Tehran',dateStyle:'medium',timeStyle:'short'}):'';}
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;}
const labels={yes:'می‌آیند',no:'نمی‌آیند',pending:'در گزارش فعلی پاسخی نیست',unknown:'نیاز به بررسی پاسخ'};
function render(){const list=build(responses,guests,excluded),s=summary(list),stats=$('#report-summary');stats.replaceChildren();for(const [n,label] of [[s.confirmed,'نفر تأییدشده'],[s.yes,'دعوت پذیرفته‌شده'],[s.no,'دعوت با پاسخ منفی'],[s.pending,'دعوت بدون پاسخ در این گزارش']]){const item=el('div',undefined,'report-stat');item.append(el('strong',fa(n)),el('span',label));stats.append(item);}$('#report-updated').textContent=meta?'آخرین دریافت: '+when(Date.parse(meta.at))+' · '+(meta.source==='google'?'دریافت از گوگل':'فایل واردشده'):responses.length?'پاسخ‌های ذخیره‌شدهٔ قبلی · زمان دریافت مشخص نیست':'هنوز پاسخی وارد این گزارش نشده؛ این عبارت به معنی پاسخ‌ندادن مهمان‌ها نیست.';$('#report-duplicates').textContent=s.duplicates?fa(s.duplicates)+' ارسال اضافه برای دعوت‌های تکرارشده در جمع نفرات شمرده نشده است؛ آخرین پاسخ هر دعوت ملاک است.':'';
const query=$('#report-search').value.trim(),filter=$('#report-filter').value,visible=list.filter(r=>(!query||(r.name+' '+r.messages.join(' ')).includes(query))&&(!filter||r.status===filter)),container=$('#response-cards');container.replaceChildren();if(!visible.length)container.append(el('p',list.length?'موردی با این جست‌وجو پیدا نشد.':'پس از دریافت پاسخ‌ها، نام، تعداد و پیام هر مهمان اینجا دیده می‌شود.','empty-report'));
for(const r of visible){const card=el('article',undefined,'response-card'),head=el('div',undefined,'response-heading');head.append(el('h3',r.name),el('span',labels[r.status],'response-badge '+r.status));card.append(head);const counts=el('p',undefined,'response-counts');counts.textContent='دعوت اولیه: '+(r.invited!==''&&r.invited!==null?fa(r.invited)+' نفر':'کارت عمومی')+' · حضور تأییدشده: '+(r.count!==null?fa(r.count)+' نفر':'—');card.append(counts);if(r.messages.length){card.append(el('p','پیام مهمان','message-label'));r.messages.forEach((msg,i)=>{if(i)card.append(el('small','پیام قبلی همین دعوت'));card.append(el('blockquote',msg));});}else if(r.status!=='pending')card.append(el('p','پیامی ننوشته‌اند.','no-message'));if(r.extras)card.append(el('p','همراهان اضافه: '+r.extras));if(r.date)card.append(el('small','آخرین پاسخ: '+when(r.date)));if(r.submissions>1)card.append(el('p',fa(r.submissions)+' بار ارسال؛ در جمع نفرات فقط یک دعوت محاسبه شده.','duplicate-note'));container.append(card);}}
root.renderWeddingReport=function(list,omitted){guests=list;if(omitted)excluded=omitted;render();};
function keep(next,source){responses=merge(responses,next);meta={at:new Date().toISOString(),source};let saved=true;try{localStorage.setItem(key,JSON.stringify(responses));localStorage.setItem(metaKey,JSON.stringify(meta));}catch{saved=false;}render();return saved;}
$('#report-search').addEventListener('input',render);$('#report-filter').addEventListener('change',render);
async function migrate(imported){
 const result=await root.WeddingConnection.call('import',imported);
 $('#report-status').textContent=fa(result.added)+' پاسخ قبلی به گوگل منتقل شد.';
 await sync();
}
$('#responses-import').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>10000000)throw Error('حجم فایل بیش از حد است.');const text=await file.text();let imported;if(file.name.toLowerCase().endsWith('.json')){const data=JSON.parse(text);imported=Array.isArray(data)?data:data.responses;if(!Array.isArray(imported)||imported.some(r=>!r||typeof r.guest_id!=='string'||!r.guest_id))throw Error('فایل پاسخ‌ها معتبر نیست.');}else imported=records(text);keep(imported,'file');$('#report-status').textContent='فایل خوانده شد؛ در حال انتقال پاسخ‌های قبلی به گوگل…';await migrate(imported);}catch(error){$('#report-status').textContent='انتقال به گوگل کامل نشد: '+error.message+' پاسخ‌های خوانده‌شده در گزارش این مرورگر حفظ شده‌اند.';}finally{e.target.value='';}});
async function sync(){if(busy)return;busy=true;$('#sync-now').disabled=true;$('#report-status').textContent='در حال دریافت پاسخ‌های مهمان‌ها…';try{const data=await root.WeddingConnection.call('read');if(!Array.isArray(data.responses))throw Error('پاسخ سرویس معتبر نیست.');const saved=keep(data.responses,'google');$('#report-status').textContent='متصل به گوگل؛ پاسخ‌ها هنگام بازبودن پنل هر ۳۰ ثانیه به‌روز می‌شوند.'+(saved?'':' ذخیرهٔ مرورگر ممکن نشد؛ گزارش را دریافت کن.');}catch(error){$('#report-status').textContent=error.message+' گزارش قبلی حفظ شده است. برای دریافت گزارش با جیمیل مالک وارد گوگل باشید.';}finally{busy=false;$('#sync-now').disabled=false;}}
$('#sync-now').addEventListener('click',sync);
$('#migrate-responses').addEventListener('click',async()=>{if(!responses.length){$('#report-status').textContent='ابتدا فایل پاسخ‌های قبلی را وارد کنید.';return;}const button=$('#migrate-responses');button.disabled=true;$('#report-status').textContent='در حال انتقال پاسخ‌های ذخیره‌شده به گوگل…';try{await migrate(responses);}catch(error){$('#report-status').textContent=error.message+' پاسخ‌های قبلی حفظ شده‌اند.';}finally{button.disabled=false;}});
setInterval(()=>{if(!document.hidden)sync();},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync();});setTimeout(sync,0);
$('#report-export').addEventListener('click',()=>{const all=[['دعوت‌شونده','دعوت اولیه','تأییدشده','وضعیت','پیام‌ها','همراهان اضافه','آخرین پاسخ','شناسه'],...build(responses,guests,excluded).map(r=>[r.name,r.invited,r.count,labels[r.status],r.messages.join('\n\n'),r.extras,when(r.date),r.id])];const url=URL.createObjectURL(new Blob(['\uFEFF'+all.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=el('a');a.href=url;a.download='negar-hossein-attendance.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);});
})(typeof window==='undefined'?{}:window);
