(() => {
'use strict';
const $=s=>document.querySelector(s),fa=n=>new Intl.NumberFormat('fa-IR').format(n);
const params=new URLSearchParams(location.hash.startsWith('#invite=')?location.hash.slice(8):location.search);
const invite=WeddingGuests.invitation(params),personal=!!invite.seats;
if(!personal){try{invite.id=sessionStorage.getItem('wedding-general-id')||'general-'+crypto.randomUUID();sessionStorage.setItem('wedding-general-id',invite.id);}catch{invite.id='general-'+Date.now()+'-'+Math.random().toString(36).slice(2);}}
$('#hero-guest').textContent=invite.name;$('#hero-guest').hidden=!personal;$('#invited-label').hidden=!personal;$('#guest-id').value=invite.id;$('#rsvp-name').value=invite.name==='مهمان گرامی'?'':invite.name;
const capacity=personal?`این دعوت، با مهر برای ${fa(invite.seats)} نفر از شما عزیزان است.`:'';
$('#invited-label').textContent=capacity;$('#rsvp-capacity').textContent=personal?capacity:'لطفاً تعداد کل افرادی را که همراه شما می‌آیند، با احتساب خودتان انتخاب کنید.';
const rows=[['۱۹:۰۰ تا ۲۲:۰۰','آغازِ دیدار و شیرینیِ جشن','از ساعت هفت تا ده شب، با شیرینی و شادی پذیرای شما هستیم؛ بانوان عزیز در سالن بانوان و آقایان گرامی در سالن آقایان، هر کدام در فضایی جداگانه، مهمان جشن ما خواهند بود.'],['۲۲:۰۰','شام را مهمان ما باشید','ساعت ده شب، سفرهٔ شام به افتخار حضور شما عزیزان آماده است؛ خوشحالیم که میزبانتان هستیم.'],['۲۲:۳۰ تا سپیده‌دم','ادامهٔ شادی؛ همه در کنار هم','از ده‌ونیم، خانم‌ها و آقایان همراه خانواده‌ها کنار هم جمع می‌شویم؛ با موسیقی، رقص و خنده، تا هرقدر که دل‌هایمان هوای جشن داشته باشد… تا سپیده‌دم.']];
if(invite.tier==='aqd')rows.unshift(['۱۸:۰۰ تا ۱۹:۰۰','لحظهٔ پیوند ما','کنار سفرهٔ عقد، دعای خیر شما بدرقهٔ آغاز زندگی‌مان خواهد بود.']);
$('#timeline').replaceChildren(...rows.map(([time,title,note])=>{const item=document.createElement('div');item.className='timeline-item';const clock=document.createElement('div');clock.className='timeline-time';clock.textContent=time;const copy=document.createElement('div');copy.className='timeline-copy';const strong=document.createElement('strong');strong.textContent=title;const span=document.createElement('span');span.textContent=note;copy.append(strong,span);item.append(clock,copy);return item;}));
const music=$('#music'),control=$('#music-control');let userPaused=false;
function sync(){const playing=!music.paused;control.classList.toggle('paused',!playing);control.setAttribute('aria-pressed',String(playing));control.setAttribute('aria-label',playing?'توقف موسیقی':'پخش موسیقی');$('#music-label').textContent=playing?'موسیقی روشن':'پخش موسیقی';}
const play=()=>{if(!userPaused)music.play().catch(sync);};music.addEventListener('play',sync);music.addEventListener('pause',sync);music.addEventListener('error',()=>{$('#music-label').textContent='پخش دوبارهٔ موسیقی';});
control.addEventListener('click',()=>{if(music.paused){userPaused=false;play();}else{userPaused=true;music.pause();}});
document.addEventListener('pointerdown',e=>{if(!e.target.closest('#music-control'))play();},{once:true});document.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&!e.target.closest('#music-control'))play();},{once:true});play();
const reduced=matchMedia('(prefers-reduced-motion: reduce)'),panels=[...document.querySelectorAll('.focus-content')];let scheduled=false;
function paint(){scheduled=false;if($('#card').hidden)return;const vh=window.innerHeight;for(const panel of panels){const rect=panel.getBoundingClientRect();if(rect.bottom < -vh||rect.top > vh*2)continue;const inside=rect.top<=vh*.6&&rect.bottom>=vh*.38;const gap=inside?0:Math.min(Math.abs(rect.top-vh*.6),Math.abs(rect.bottom-vh*.38));const amount=Math.min(1,gap/(vh*.48));panel.style.setProperty('--focus-blur',reduced.matches?'0px':`${(amount*3).toFixed(2)}px`);panel.style.setProperty('--focus-opacity',reduced.matches?'1':String(1-amount*.55));panel.style.setProperty('--focus-y',reduced.matches?'0px':`${(rect.top>vh*.6?1:-1)*amount*14}px`);}document.documentElement.style.setProperty('--bird-y',`${Math.sin(window.scrollY/650)*28}px`);}
function queue(){if(!scheduled){scheduled=true;requestAnimationFrame(paint);}}window.addEventListener('scroll',queue,{passive:true});window.addEventListener('resize',queue,{passive:true});reduced.addEventListener('change',queue);
$('#enter-button').addEventListener('click',()=>{
 $('#enter-button').disabled=true;play();$('#card').hidden=false;window.scrollTo(0,0);window.WeddingGarden?.start();
 $('#gate').classList.add('leaving');$('#card').classList.add('arriving');queue();
 setTimeout(()=>{$('#gate').hidden=true;document.body.classList.remove('gate-open');$('#card').classList.remove('arriving');$('.couple-title').focus({preventScroll:true});queue();},reduced.matches?0:2400);
});
const wedding=new Date(invite.tier==='aqd'?'2026-10-14T18:00:00+03:30':'2026-10-14T19:00:00+03:30').getTime();function tick(){const d=Math.max(0,wedding-Date.now());Object.entries({days:Math.floor(d/86400000),hours:Math.floor(d/3600000)%24,minutes:Math.floor(d/60000)%60,seconds:Math.floor(d/1000)%60}).forEach(([k,v])=>$(`[data-unit="${k}"]`).textContent=fa(v));}tick();setInterval(tick,1000);
const form=$('#rsvp-form'),count=$('#confirmed-count'),extras=$('#extra-guests'),status=$('#form-status');for(let i=1;i<=(personal?invite.seats*2:WeddingGuests.generalLimit);i++)count.add(new Option(`${fa(i)} نفر`,String(i)));count.value=String(invite.seats||1);$('#count-field').hidden=false;
function renderExtras(){const needed=!personal||count.disabled?0:Math.max(0,Number(count.value)-invite.seats);while(extras.children.length>needed)extras.lastElementChild.remove();while(extras.children.length<needed){const i=extras.children.length+1,field=document.createElement('fieldset');field.className='extra-person';field.innerHTML=`<legend>همراه اضافهٔ ${fa(i)}</legend><label>نام و نام خانوادگی همراه ${fa(i)}<input name="extra_${i}_name" maxlength="100" autocomplete="off" required></label><label>نسبت همراه ${fa(i)} با شما<input name="extra_${i}_relationship" maxlength="100" placeholder="مثلاً خواهر، فرزند یا دوست" required></label>`;extras.append(field);}queue();}
count.addEventListener('change',renderExtras);form.querySelectorAll('[name=attendance]').forEach(r=>r.addEventListener('change',()=>{const yes=form.elements.attendance.value==='yes';$('#attendance-details').hidden=!yes;count.disabled=!yes;if(!yes)count.value='1';renderExtras();}));
let submitting=false;form.addEventListener('submit',async e=>{e.preventDefault();if(submitting||!form.reportValidity())return;status.className='form-status';let payload;try{payload=WeddingGuests.response(invite,form.elements.attendance.value,count.value,[...extras.children].map(f=>({name:f.querySelector('input').value,relationship:f.querySelectorAll('input')[1].value})));}catch(error){status.textContent=error.message;status.classList.add('error');return;}
if(!personal)payload.invitation_name=form.elements.name.value.trim();submitting=true;const button=form.querySelector('[type=submit]');button.disabled=true;status.textContent='در حال ثبت پاسخ مهربان شما…';
const body=new FormData(form);body.set('response_time',new Date().toISOString());Object.entries(payload).forEach(([k,v])=>body.set(k,k==='additional_guests'?JSON.stringify(v):v===null?'':String(v)));body.set('تعداد دعوت‌شده',personal?String(invite.seats):'در کارت عمومی مشخص نشده');body.set('تعداد تأییدشده',String(payload.confirmed_count));body.set('خلاصه پاسخ',`${payload.invitation_name} | دعوت: ${personal?invite.seats:'عمومی'} | تأیید: ${payload.confirmed_count} نفر | ${payload.attendance==='yes'?'می‌آیند':'نمی‌آیند'}`);
const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{const response=await fetch(form.action,{method:'POST',body,headers:{Accept:'application/json'},signal:controller.signal});if(!response.ok)throw Error();status.className='form-status success';status.textContent=payload.confirmed_count?`پاسخ شما ثبت شد؛ با عشق چشم‌به‌راه ${fa(payload.confirmed_count)} نفر از شما عزیزان هستیم. ♡`:'پاسخ شما ثبت شد؛ جای شما سبز و مهرتان همیشه همراه ماست. ♡';}catch{status.className='form-status error';status.textContent='هنوز تأیید ثبت را دریافت نکردیم. لطفاً اتصال را بررسی کنید و دوباره بزنید.';}finally{clearTimeout(timer);submitting=false;button.disabled=false;queue();}});
})();
